default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: postgres

development:
  <<: *default
  database: hellohellorails_development

test:
  <<: *default
  database: hellohellorails_test
production:
  <<: *default
  database: hellohellorails_production
  username: hellohellorails
  password: <%= ENV["HELLOHELLORAILS_DATABASE_PASSWORD"] %>
